/* Seed network for the live prototype. Mirrors prisma/seed.ts. */
import type { State, Person, Relationship, Evidence, Conversation, Opportunity, Introduction, TeamMember, Partner, PartnerRequirement, Relocation, Scheduled, AuditEntry, Account, StoredBrief, ShortlistItem, FeeLine, Vouch, Referral, Pitch } from "./types";
import { parseBrief, defaultFeeModel, defaultTerms, DEFAULT_RATE_CARD } from "@/lib/demand";
import type { ShortlistDecision } from "@/lib/demand";
import { SCREENING_SCRIPT } from "@/lib/screening";
import type { AvailabilityStatus, EngagementRoute, Seniority } from "@prisma/client";
import { suggestNextCheck } from "@/lib/availability";

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();
const daysAhead = (n: number) => new Date(Date.now() + n * 86_400_000).toISOString();

export const USERS = [
  { id: "u-waqas", name: "Waqas Anwar", role: "OWNER" as const },
  { id: "u-richard", name: "Richard Cole", role: "CONTRIBUTOR" as const },
  { id: "u-soban", name: "Soban Malik", role: "CONTRIBUTOR" as const },
];

type SP = { key: string; firstName: string; lastName: string; headline: string; company: string; role: string; city: string; country: string; target?: string[]; caps: string[]; sectors: string[]; seniority: Seniority; routes: EngagementRoute[]; rate?: string; salary?: string; rights?: string[]; screened?: number; registered?: number; attrs?: Record<string, number>; status: AvailabilityStatus; confirmed: number | null; reloc?: boolean; bench?: boolean; used?: boolean; email?: string; next?: string; nextIn?: number };
const P: SP[] = [
  { key: "sarah", attrs: { assertiveness: 5, conflict: 5, political: 4, commercial: 4, collaboration: 3, ambiguity: 4, influence: 5, pace: 4 }, screened: 40, rights: ["Right to work in UK"], firstName: "Sarah", lastName: "Okonkwo", headline: "Programme director who stabilises troubled transformations", company: "Independent", role: "Programme Director", city: "London", country: "UK", target: ["Dubai", "Riyadh"], caps: ["Programme director", "Transformation", "Systems integrator challenge", "Turnaround", "Stakeholder management"], sectors: ["Banking", "Financial services"], seniority: "DIRECTOR", routes: ["INTERIM", "CONTRACT", "SOW"], rate: "£1,350/day", status: "FINISHING_ENGAGEMENT_SOON", confirmed: 6, reloc: true, bench: true, used: true, email: "sarah.okonkwo@example.com", next: "Confirm end date of current programme", nextIn: 3 },
  { key: "daniel", rights: ["Right to work in UK"], firstName: "Daniel", lastName: "Reyes", headline: "CISO / security architecture, regulated industries", company: "Northgate Insurance", role: "Deputy CISO", city: "Manchester", country: "UK", caps: ["Cyber security", "Security architecture", "CISO", "Identity and access", "Regulatory"], sectors: ["Insurance", "Financial services"], seniority: "EXECUTIVE", routes: ["FRACTIONAL", "ADVISORY", "PERMANENT"], salary: "£185k", status: "QUIETLY_EXPLORING", confirmed: 20, bench: true, email: "daniel.reyes@example.com", next: "Send fractional CISO framing", nextIn: 5 },
  { key: "amira", rights: ["UAE residence visa"], firstName: "Amira", lastName: "Haddad", headline: "Data platform and AI delivery lead", company: "Gulf Capital Partners", role: "Head of Data", city: "Dubai", country: "UAE", caps: ["Data platform", "Data engineering", "AI", "Machine learning", "Azure", "Delivery lead"], sectors: ["Sovereign wealth", "Financial services"], seniority: "SENIOR_MANAGER", routes: ["PERMANENT", "SOW"], salary: "AED 65k/month", status: "RIGHT_OPPORTUNITY_ONLY", confirmed: 35, bench: true, used: true, email: "amira.haddad@example.com" },
  { key: "tom", attrs: { assertiveness: 4, conflict: 3, political: 4, commercial: 5, collaboration: 4, ambiguity: 4, influence: 4, pace: 3 }, screened: 50, rights: ["Right to work in UK"], firstName: "Tom", lastName: "Whitfield", headline: "Fractional CFO for scale-ups and carve-outs", company: "Whitfield Advisory", role: "Fractional CFO", city: "Edinburgh", country: "UK", caps: ["Finance transformation", "CFO", "M&A integration", "Commercial", "Governance"], sectors: ["Technology", "Retail"], seniority: "EXECUTIVE", routes: ["FRACTIONAL", "ADVISORY"], rate: "£1,600/day", status: "FRACTIONAL_AVAILABILITY", confirmed: 12, email: "tom.whitfield@example.com" },
  { key: "priya", attrs: { assertiveness: 3, conflict: 4, political: 4, commercial: 3, collaboration: 5, ambiguity: 4, influence: 4, pace: 3 }, screened: 30, rights: ["Right to work in UK"], firstName: "Priya", lastName: "Natarajan", headline: "Change and target operating model lead", company: "Independent", role: "Change Director", city: "London", country: "UK", target: ["Abu Dhabi"], caps: ["Change management", "Target operating model", "Transformation", "PMO", "Stakeholder management"], sectors: ["Public sector", "Healthcare"], seniority: "DIRECTOR", routes: ["CONTRACT", "SOW", "INTERIM"], rate: "£1,100/day", status: "AVAILABLE_NOW", confirmed: 3, bench: true, used: true, email: "priya.n@example.com", next: "Introduce to Meridian if route confirmed", nextIn: 2 },
  { key: "james", rights: ["Right to work in UK"], firstName: "James", lastName: "Carrick", headline: "ERP programme lead (SAP S/4)", company: "Carrick Delivery Ltd", role: "Programme Lead", city: "Birmingham", country: "UK", caps: ["SAP", "ERP", "Programme management", "Vendor management", "Systems integrator challenge"], sectors: ["Manufacturing", "Utilities"], seniority: "DIRECTOR", routes: ["CONTRACT", "SOW"], rate: "£1,250/day", status: "NEEDS_REFRESH", confirmed: 120, email: "james.carrick@example.com", next: "Reconnect — status stale", nextIn: 1 },
  { key: "layla", rights: ["Right to work in Saudi Arabia"], firstName: "Layla", lastName: "Mansour", headline: "Enterprise architect, cloud and integration", company: "Riyadh Digital Authority", role: "Chief Architect", city: "Riyadh", country: "Saudi Arabia", caps: ["Enterprise architecture", "Cloud", "AWS", "Solution architecture", "Governance"], sectors: ["Government", "Public sector"], seniority: "EXECUTIVE", routes: ["ADVISORY", "SOW"], rate: "SAR 6,500/day", status: "SOW_ONLY", confirmed: 28, bench: true, email: "layla.mansour@example.com" },
  { key: "oliver", rights: ["Right to work in UK"], firstName: "Oliver", lastName: "Bennett", headline: "Product and agile delivery leader", company: "Fintech scale-up", role: "VP Product", city: "London", country: "UK", caps: ["Product management", "Agile delivery", "Platform engineering", "Stakeholder management"], sectors: ["Financial services", "Technology"], seniority: "SENIOR_MANAGER", routes: ["PERMANENT"], salary: "£160k + equity", status: "HAPPY_WHERE_I_AM", confirmed: 40, email: "oliver.bennett@example.com" },
  { key: "fatima", attrs: { assertiveness: 3, conflict: 3, political: 4, commercial: 3, collaboration: 4, ambiguity: 3, influence: 3, pace: 3 }, screened: 12, rights: ["UAE residence visa (own sponsorship)"], firstName: "Fatima", lastName: "Al Rashid", headline: "Cyber governance, risk and compliance", company: "Independent", role: "GRC Consultant", city: "Abu Dhabi", country: "UAE", caps: ["Cyber security", "Governance", "Risk", "Compliance", "Regulatory"], sectors: ["Energy", "Government"], seniority: "MANAGER", routes: ["CONTRACT", "SOW"], rate: "AED 4,200/day", status: "AVAILABLE_NOW", confirmed: 8, bench: true, email: "fatima.ar@example.com" },
  { key: "marcus", attrs: { assertiveness: 5, conflict: 5, political: 3, commercial: 5, collaboration: 3, ambiguity: 5, influence: 4, pace: 5 }, screened: 60, rights: ["Right to work in UK"], firstName: "Marcus", lastName: "Doyle", headline: "Interim COO, operations turnaround", company: "Independent", role: "Interim COO", city: "Leeds", country: "UK", target: ["Dubai"], caps: ["Operations", "Turnaround", "COO", "Supply chain", "Target operating model"], sectors: ["Logistics", "Retail"], seniority: "C_LEVEL", routes: ["INTERIM", "FRACTIONAL"], rate: "£1,800/day", status: "OPEN_TO_CONVERSATIONS", confirmed: 15, reloc: true, email: "marcus.doyle@example.com" },
  { key: "hannah", rights: ["Right to work in UK (settled status)"], firstName: "Hannah", lastName: "Lindqvist", headline: "GenAI strategy and responsible AI", company: "Nordic Bank", role: "Head of AI", city: "London", country: "UK", caps: ["AI", "GenAI", "Data strategy", "Governance", "Machine learning"], sectors: ["Banking", "Financial services"], seniority: "DIRECTOR", routes: ["ADVISORY", "FRACTIONAL"], rate: "£1,900/day", status: "RIGHT_OPPORTUNITY_ONLY", confirmed: 22, bench: true, email: "hannah.l@example.com" },
  { key: "ravi", rights: ["Right to work in UK"], firstName: "Ravi", lastName: "Menon", headline: "PMO and portfolio governance", company: "Carrick Delivery Ltd", role: "PMO Lead", city: "Birmingham", country: "UK", caps: ["PMO", "Project management", "Governance", "Programme management"], sectors: ["Utilities", "Manufacturing"], seniority: "MANAGER", routes: ["CONTRACT", "SOW"], rate: "£650/day", status: "OPEN_TO_CONVERSATIONS", confirmed: 50, used: true, email: "ravi.menon@example.com" },
  { key: "chloe", rights: ["Right to work in UK"], firstName: "Chloe", lastName: "Martin", headline: "ServiceNow and IT operating model", company: "Independent", role: "Platform Lead", city: "Bristol", country: "UK", caps: ["ServiceNow", "Target operating model", "Platform engineering", "Vendor management"], sectors: ["Telecoms", "Public sector"], seniority: "SENIOR_MANAGER", routes: ["CONTRACT"], rate: "£850/day", status: "CONTRACT_ONLY", confirmed: 10, email: "chloe.martin@example.com" },
  { key: "khalid", rights: ["UAE golden visa"], firstName: "Khalid", lastName: "Farouk", headline: "Bid and proposal director, GCC public sector", company: "Independent", role: "Bid Director", city: "Dubai", country: "UAE", caps: ["Bid management", "Proposal", "Commercial", "SOW", "Stakeholder management"], sectors: ["Government", "Defence"], seniority: "DIRECTOR", routes: ["SOW", "ADVISORY"], rate: "AED 5,000/day", status: "NOT_LOOKING_KEEP_IN_TOUCH", confirmed: 30, used: true, bench: true, email: "khalid.f@example.com" },
  { key: "emma", rights: ["Right to work in UK"], firstName: "Emma", lastName: "Fitzgerald", headline: "Regulatory change and compliance programmes", company: "Global Bank", role: "Head of Regulatory Change", city: "London", country: "UK", caps: ["Regulatory", "Compliance", "Programme management", "Change management"], sectors: ["Banking"], seniority: "DIRECTOR", routes: ["PERMANENT"], salary: "£175k", status: "QUIETLY_EXPLORING", confirmed: 9, email: "emma.f@example.com" },
  { key: "yusuf", rights: ["Right to work in UK", "UAE residence visa"], firstName: "Yusuf", lastName: "Demir", headline: "DevOps and platform engineering lead", company: "Independent", role: "Platform Engineering Lead", city: "London", country: "UK", target: ["Remote", "Dubai"], caps: ["DevOps", "Platform engineering", "Cloud", "Azure", "Engineering lead"], sectors: ["Technology", "Media"], seniority: "SENIOR_MANAGER", routes: ["CONTRACT", "SOW"], rate: "£900/day", status: "TAKING_A_BREAK", confirmed: 18, email: "yusuf.d@example.com" },
  { key: "grace", rights: ["Right to work in UK"], firstName: "Grace", lastName: "Adeyemi", headline: "Procurement and supply chain transformation", company: "Independent", role: "Procurement Director", city: "London", country: "UK", caps: ["Procurement", "Supply chain", "Transformation", "Commercial", "Vendor management"], sectors: ["Retail", "Consumer", "Public sector"], seniority: "DIRECTOR", routes: ["INTERIM", "CONTRACT"], rate: "£1,000/day", status: "NEEDS_REFRESH", confirmed: null, email: "grace.a@example.com", next: "First proper conversation not yet held", nextIn: 4 },
  { key: "nadia", attrs: { assertiveness: 4, conflict: 3, political: 3, commercial: 3, collaboration: 5, ambiguity: 3, influence: 4, pace: 4 }, screened: 20, rights: ["UAE residence visa"], firstName: "Nadia", lastName: "Rahman", headline: "Senior business analyst, core banking and payments", company: "Emirates Digital Bank", role: "Lead Business Analyst", city: "Dubai", country: "UAE", caps: ["Business analysis", "Requirements", "Core banking", "Payments", "Agile delivery"], sectors: ["Banking", "Financial services"], seniority: "SENIOR_MANAGER", routes: ["PERMANENT", "CONTRACT"], salary: "AED 420k", status: "OPEN_TO_CONVERSATIONS", confirmed: 9, email: "nadia.rahman@example.com" },
  { key: "omar", rights: ["UAE residence visa"], firstName: "Omar", lastName: "Haddad", headline: "Business analyst turned product owner, retail banking", company: "Independent", role: "Business Analyst", city: "Dubai", country: "UAE", caps: ["Business analysis", "Product ownership", "Retail banking", "Process mapping"], sectors: ["Banking"], seniority: "MANAGER", routes: ["CONTRACT", "PERMANENT"], rate: "AED 2,400/day", salary: "AED 300k", status: "AVAILABLE_NOW", confirmed: 4 },
  { key: "isha", rights: ["UAE employment visa (sponsored by current employer)"], firstName: "Isha", lastName: "Verma", headline: "Project manager, digital banking programmes", company: "Gulf Retail Bank", role: "Senior Project Manager", city: "Abu Dhabi", country: "UAE", caps: ["Project management", "Digital banking", "Agile delivery", "Vendor management"], sectors: ["Banking"], seniority: "SENIOR_MANAGER", routes: ["PERMANENT"], salary: "AED 480k", status: "QUIETLY_EXPLORING", confirmed: 18 },
  { key: "leila", firstName: "Leila", lastName: "Osman", headline: "Registered via the member link — regulatory change, insurance", company: "Unknown", role: "Regulatory Change Manager", city: "London", country: "UK", caps: ["Regulatory", "Change management"], sectors: ["Insurance"], seniority: "MANAGER", routes: [], status: "NEEDS_REFRESH", confirmed: null, next: "Screening call", nextIn: 2, registered: 1, email: "leila@example.com" },
  { key: "ben", firstName: "Ben", lastName: "Hughes", headline: "Referred by Sarah — programme recovery, SI management", company: "Unknown", role: "Programme Manager", city: "London", country: "UK", caps: ["Programme management", "Recovery", "Systems integrator challenge"], sectors: ["Insurance"], seniority: "SENIOR_MANAGER", routes: [], status: "NEEDS_REFRESH", confirmed: null, next: "Book intro conversation", nextIn: 2 },
];
const pid = (k: string) => `p-${k}`;

export function seed(): State {
  const people: Person[] = P.map((p, i) => {
    const confirmedAt = p.confirmed === null ? null : daysAgo(p.confirmed);
    return {
      id: pid(p.key), firstName: p.firstName, lastName: p.lastName, email: p.email ?? null, headline: p.headline, currentCompany: p.company, currentRole: p.role, primaryCity: p.city, primaryCountry: p.country,
      targetLocations: p.target ?? [], capabilities: p.caps, sectors: p.sectors, seniority: p.seniority, engagementPreferences: p.routes, rateExpectation: p.rate ?? null, salaryExpectation: p.salary ?? null,
      availabilityStatus: p.status, availabilityConfirmedAt: confirmedAt, availabilitySource: confirmedAt ? "conversation" : null, availabilityConfidence: confirmedAt ? 80 : 30,
      nextCheckDate: confirmedAt ? suggestNextCheck(p.status, new Date(confirmedAt)).toISOString() : null,
      workRights: p.rights ?? [], attributes: p.attrs ?? null, screenedAt: p.screened ? daysAgo(p.screened) : null, screeningStatus: p.screened ? "APPROVED" : p.registered ? "REGISTERED" : "NONE", referralConsent: p.screened ? "yes" : null, memberSince: p.screened ? daysAgo(p.screened) : p.registered ? daysAgo(p.registered) : null, relocationInterest: p.reloc ?? false, amanaBench: p.bench ?? false, usedByAmana: p.used ?? false, nextAction: p.next ?? null, nextActionDate: p.next ? daysAhead(p.nextIn ?? 3) : null,
      createdAt: daysAgo(200 - i * 9), updatedAt: daysAgo(p.confirmed ?? 60),
    };
  });
  const R = (key: string, owner: string, r: Partial<Relationship> & { sourceType: Relationship["sourceType"]; relationshipType: Relationship["relationshipType"] }, idx: number): Relationship => ({ id: `r-${key}-${idx}`, personId: pid(key), networkOwnerId: owner, workedTogether: false, ...r });
  const relationships: Relationship[] = [
    R("sarah", "u-waqas", { sourceType: "WORKED_TOGETHER", relationshipType: "WORKED_WITH", workedTogether: true, workedTogetherContext: "Core banking replacement programme, 2021–2022. Took a red programme to amber in a quarter.", yearsKnown: 6, wouldWorkTogetherAgain: true, relationshipNotes: "Direct, no-nonsense. Do not position on greenfield builds. Prefers a call over email.", lastContactDate: daysAgo(6) }, 1),
    R("daniel", "u-waqas", { sourceType: "PERSONAL_NETWORK", relationshipType: "DIRECT", yearsKnown: 4, relationshipNotes: "Met through the CISO round table. Equity vesting cliff in Q1.", lastContactDate: daysAgo(20) }, 1),
    R("amira", "u-richard", { sourceType: "CLIENT", relationshipType: "CLIENT_OF", workedTogether: true, workedTogetherContext: "Amana data platform SOW, 2024.", yearsKnown: 2, wouldWorkTogetherAgain: true, relationshipNotes: "Excellent with executive stakeholders.", lastContactDate: daysAgo(35) }, 1),
    R("tom", "u-waqas", { sourceType: "INTRODUCTION", introducedById: pid("sarah"), relationshipType: "INTRODUCED", yearsKnown: 1, relationshipNotes: "Sarah rates him for carve-outs.", lastContactDate: daysAgo(12) }, 1),
    R("priya", "u-waqas", { sourceType: "WORKED_TOGETHER", relationshipType: "MANAGED", workedTogether: true, workedTogetherContext: "NHS trust operating model redesign — ran the change workstream for me.", yearsKnown: 5, wouldWorkTogetherAgain: true, relationshipNotes: "Calm under pressure. Wants a Gulf move within 12 months.", lastContactDate: daysAgo(3) }, 1),
    R("priya", "u-soban", { sourceType: "WORKED_TOGETHER", relationshipType: "PEER", workedTogether: true, workedTogetherContext: "Amana public sector SOW, 2025.", yearsKnown: 1, wouldWorkTogetherAgain: true, lastContactDate: daysAgo(30) }, 2),
    R("james", "u-waqas", { sourceType: "PERSONAL_NETWORK", relationshipType: "KNOWS_OF", yearsKnown: 3, relationshipNotes: "Solid SAP lead by reputation.", lastContactDate: daysAgo(120) }, 1),
    R("layla", "u-soban", { sourceType: "CLIENT", relationshipType: "CLIENT_OF", workedTogether: true, workedTogetherContext: "Architecture review for a Riyadh government entity.", yearsKnown: 2, wouldWorkTogetherAgain: true, relationshipNotes: "Advisory only; will not do hands-on delivery.", lastContactDate: daysAgo(28) }, 1),
    R("oliver", "u-waqas", { sourceType: "EVENT", relationshipType: "DIRECT", yearsKnown: 2, lastContactDate: daysAgo(40) }, 1),
    R("fatima", "u-richard", { sourceType: "PARTNER_REFERRAL", introducedById: pid("layla"), relationshipType: "INTRODUCED", yearsKnown: 1, relationshipNotes: "Layla vouches for her GRC work.", lastContactDate: daysAgo(8) }, 1),
    R("marcus", "u-waqas", { sourceType: "WORKED_TOGETHER", relationshipType: "WORKED_WITH", workedTogether: true, workedTogetherContext: "Logistics turnaround, 2019.", yearsKnown: 7, wouldWorkTogetherAgain: true, relationshipNotes: "Blunt. Great in a crisis, bored in steady state.", lastContactDate: daysAgo(15) }, 1),
    R("hannah", "u-waqas", { sourceType: "INTRODUCTION", introducedById: pid("daniel"), relationshipType: "INTRODUCED", yearsKnown: 1, relationshipNotes: "Strong on responsible AI governance.", lastContactDate: daysAgo(22) }, 1),
    R("ravi", "u-waqas", { sourceType: "WORKED_TOGETHER", relationshipType: "MANAGED", workedTogether: true, workedTogetherContext: "PMO lead on my utilities programme.", yearsKnown: 4, wouldWorkTogetherAgain: true, lastContactDate: daysAgo(50) }, 1),
    R("chloe", "u-soban", { sourceType: "LINKEDIN", relationshipType: "DIRECT", yearsKnown: 1, lastContactDate: daysAgo(10) }, 1),
    R("khalid", "u-richard", { sourceType: "WORKED_TOGETHER", relationshipType: "WORKED_WITH", workedTogether: true, workedTogetherContext: "Two Amana bids in 2025, both won.", yearsKnown: 3, wouldWorkTogetherAgain: true, relationshipNotes: "Our go-to for GCC public sector bids.", lastContactDate: daysAgo(30) }, 1),
    R("emma", "u-waqas", { sourceType: "PERSONAL_NETWORK", relationshipType: "PEER", yearsKnown: 8, relationshipNotes: "Must not be approached via her employer.", lastContactDate: daysAgo(9) }, 1),
    R("yusuf", "u-waqas", { sourceType: "WORKED_TOGETHER", relationshipType: "WORKED_WITH", workedTogether: true, workedTogetherContext: "Platform rebuild for a media client.", yearsKnown: 3, wouldWorkTogetherAgain: false, relationshipNotes: "Clashed badly with the client PMO.", lastContactDate: daysAgo(18) }, 1),
    R("grace", "u-waqas", { sourceType: "INBOUND", relationshipType: "KNOWS_OF", yearsKnown: 0, relationshipNotes: "Reached out after a talk. Not yet spoken.", lastContactDate: daysAgo(4) }, 1),
    R("leila", "u-waqas", { sourceType: "INBOUND", relationshipType: "KNOWS_OF", introducedById: pid("emma"), relationshipNotes: "Registered through Emma's invite link. Screening not yet done.", lastContactDate: daysAgo(1) }, 1),
    R("nadia", "u-waqas", { sourceType: "WORKED_TOGETHER", relationshipType: "WORKED_WITH", workedTogether: true, workedTogetherContext: "Payments platform programme in Dubai, 2023. Ran the requirements workstream.", yearsKnown: 3, wouldWorkTogetherAgain: true, relationshipNotes: "Precise, calm, well liked by the business. Wants to stay in Dubai.", lastContactDate: daysAgo(9) }, 1),
    R("omar", "u-richard", { sourceType: "INTRODUCTION", introducedById: pid("nadia"), relationshipType: "INTRODUCED", yearsKnown: 1, relationshipNotes: "Nadia rates him; worked under her on payments.", lastContactDate: daysAgo(4) }, 1),
    R("isha", "u-waqas", { sourceType: "EVENT", relationshipType: "DIRECT", yearsKnown: 2, relationshipNotes: "Met at the Abu Dhabi fintech forum. Sponsored by current employer; move would need a visa transfer.", lastContactDate: daysAgo(18) }, 1),
    R("ben", "u-waqas", { sourceType: "INTRODUCTION", introducedById: pid("sarah"), relationshipType: "INTRODUCED", yearsKnown: 0, relationshipNotes: "Sarah says he ran SI recovery under her. Referral only.", lastContactDate: daysAgo(2) }, 1),
  ];
  const E = (key: string, observer: string, e: Omit<Evidence, "id" | "personId" | "observerId" | "visibility"> & { visibility?: Evidence["visibility"] }, idx: number): Evidence => ({ id: `e-${key}-${idx}`, personId: pid(key), observerId: observer, visibility: "TENANT", ...e });
  const evidence: Evidence[] = [
    E("sarah", "u-waqas", { evidenceType: "DELIVERY_OBSERVED", context: "Transformation programme recovery, banking", description: "Took a red core-banking programme to amber within one quarter; re-baselined the SI contract.", confidence: 95, dateObserved: daysAgo(900), visibility: "PARTNER_SAFE" }, 1),
    E("sarah", "u-waqas", { evidenceType: "CLIENT_FEEDBACK", context: "Systems integrator challenge", description: "CIO said she was 'the only person the SI was afraid of'.", confidence: 85, dateObserved: daysAgo(800) }, 2),
    E("priya", "u-waqas", { evidenceType: "DELIVERY_OBSERVED", context: "Change management, healthcare operating model", description: "Ran the change workstream across 14 clinical directorates; adoption above target.", confidence: 90, dateObserved: daysAgo(600), visibility: "PARTNER_SAFE" }, 1),
    E("priya", "u-soban", { evidenceType: "OUTCOME", context: "Public sector SOW", description: "Amana SOW delivered on time; client extended by three months.", confidence: 85, dateObserved: daysAgo(120) }, 2),
    E("amira", "u-richard", { evidenceType: "DELIVERY_OBSERVED", context: "Data platform, Azure", description: "Led the Azure data platform build; strong executive stakeholder handling.", confidence: 90, dateObserved: daysAgo(400) }, 1),
    E("marcus", "u-waqas", { evidenceType: "DELIVERY_OBSERVED", context: "Operations turnaround, logistics", description: "Cut backlog by 60% in 8 weeks; rebuilt the shift model.", confidence: 90, dateObserved: daysAgo(2000) }, 1),
    E("khalid", "u-richard", { evidenceType: "OUTCOME", context: "Bid management, GCC public sector", description: "Two Amana bids won with Khalid leading the proposal.", confidence: 95, dateObserved: daysAgo(200) }, 1),
    E("layla", "u-soban", { evidenceType: "CLIENT_FEEDBACK", context: "Enterprise architecture, government", description: "Her review was the reason the client paused a failing migration.", confidence: 80, dateObserved: daysAgo(300) }, 1),
    E("ravi", "u-waqas", { evidenceType: "DELIVERY_OBSERVED", context: "PMO governance", description: "Reliable PMO; portfolio reporting from monthly to weekly.", confidence: 75, dateObserved: daysAgo(900) }, 1),
    E("yusuf", "u-waqas", { evidenceType: "DELIVERY_OBSERVED", context: "Platform engineering", description: "Delivered a solid CI/CD platform rebuild.", confidence: 85, dateObserved: daysAgo(500) }, 1),
    E("yusuf", "u-waqas", { evidenceType: "CAUTION", context: "Stakeholder handling", description: "Repeated conflict with client PMO; needs a strong delivery lead above him.", confidence: 85, dateObserved: daysAgo(480), visibility: "PRIVATE" }, 2),
    E("fatima", "u-richard", { evidenceType: "REFERENCE", context: "Cyber GRC, energy regulator", description: "Layla Mansour vouches for her GRC delivery.", confidence: 65, dateObserved: daysAgo(60) }, 1),
    E("daniel", "u-waqas", { evidenceType: "PEER_FEEDBACK", context: "Security architecture", description: "Two CISOs independently described his identity programme as best in class.", confidence: 70, dateObserved: daysAgo(100) }, 1),
  ];
  evidence.push(E("nadia", "u-waqas", { evidenceType: "DELIVERY_OBSERVED", context: "Business analysis, payments, banking", description: "Owned the requirements for a payments hub; zero defects traced to requirements at go-live.", confidence: 90, dateObserved: daysAgo(500), visibility: "PARTNER_SAFE" }, 1));
  const S = (o: Partial<import("@/lib/ai/types").ExtractedSummary>) => ({ headline: "", capabilities: [], sectors: [], engagementPreferences: [], locationPreferences: [], currentStatus: "", ratesOrSalary: "", workingCharacteristics: [], constraints: [], strengths: [], avoid: [], unresolvedQuestions: [], summary: "", ...o }) as import("@/lib/ai/types").ExtractedSummary;
  const C = (key: string, by: string, c: Partial<Conversation> & { date: string; approvalStatus: Conversation["approvalStatus"] }, idx: number): Conversation => ({ id: `c-${key}-${idx}`, personId: pid(key), conductedById: by, type: "CATCH_UP", tags: [], ...c });
  const conversations: Conversation[] = [
    C("sarah", "u-waqas", { date: daysAgo(6), rawNotes: "Sarah is finishing the current programme at the end of next month. Wants another recovery, ideally banking or insurance. Open to Dubai for the right client, family would follow. Day rate £1,350, could flex for a 12-month SOW. Does not want a greenfield build. Follow up in three weeks.", approvalStatus: "APPROVED", followUpDate: daysAhead(15), approvedSummary: S({ headline: "Programme recovery specialist, finishing engagement next month", capabilities: ["programme director", "transformation", "systems integrator challenge", "turnaround"], sectors: ["banking", "insurance"], engagementPreferences: ["INTERIM", "SOW"], locationPreferences: ["london", "dubai"], currentStatus: "Finishing current programme at end of next month", suggestedAvailabilityStatus: "FINISHING_ENGAGEMENT_SOON", ratesOrSalary: "£1,350/day, flexible for 12-month SOW", workingCharacteristics: ["Direct", "Best in recovery situations"], constraints: ["No greenfield builds"], strengths: ["Taking red programmes to amber", "Managing systems integrators"], avoid: ["Greenfield builds"], followUpDate: "in three weeks", unresolvedQuestions: ["Exact end date of current programme"], summary: "Finishing next month; wants recovery work in banking/insurance; open to Dubai." }) }, 1),
    C("priya", "u-waqas", { date: daysAgo(3), rawNotes: "Priya rolled off last Friday and is available now. Actively wants a Gulf move within 12 months — school places are the constraint. Prefers SOW or contract. £1,100/day. Keen on Abu Dhabi. Asked about the relocation advisory.", approvalStatus: "APPROVED", followUpDate: daysAhead(7), approvedSummary: S({ headline: "Change director, available now, wants Gulf move within 12 months", capabilities: ["change management", "target operating model", "transformation"], sectors: ["public sector", "healthcare"], engagementPreferences: ["SOW", "CONTRACT", "INTERIM"], locationPreferences: ["abu dhabi", "uae"], currentStatus: "Available now", suggestedAvailabilityStatus: "AVAILABLE_NOW", ratesOrSalary: "£1,100/day", workingCharacteristics: ["Calm under pressure", "Strong with clinicians"], constraints: ["School places — September intake"], strengths: ["Large-scale change adoption"], unresolvedQuestions: ["AED rate expectation"], summary: "Available now; SOW/contract preferred; Abu Dhabi move within 12 months." }) }, 1),
    C("daniel", "u-waqas", { date: daysAgo(20), type: "INTRO_CALL", rawNotes: "Daniel is quietly exploring. Would consider a fractional CISO role two days a week, or a full move for a Group CISO title. Equity cliff in Q1 so nothing before then. Strong on identity. Package £185k. Don't approach via his employer.", approvalStatus: "NEEDS_REVIEW", aiSummary: S({ headline: "Deputy CISO quietly exploring; fractional or Group CISO", capabilities: ["ciso", "cyber security", "identity and access"], sectors: ["insurance", "financial services"], engagementPreferences: ["FRACTIONAL", "PERMANENT"], locationPreferences: ["manchester", "uk"], currentStatus: "Quietly exploring; equity cliff in Q1", suggestedAvailabilityStatus: "QUIETLY_EXPLORING", ratesOrSalary: "£185k package", workingCharacteristics: ["Thoughtful", "Low profile"], constraints: ["Nothing before Q1 vesting", "Do not approach via employer"], strengths: ["Identity programmes"], unresolvedQuestions: ["Would his employer permit a fractional arrangement?", "Rate for fractional work?"], summary: "Quietly exploring; fractional CISO or Group CISO; nothing before Q1." }) }, 1),
    C("marcus", "u-waqas", { date: daysAgo(15), rawNotes: "Marcus is between engagements and open to conversations. Interested in Dubai — family would move. Interim COO roles or fractional. £1,800/day. Needs a burning platform.", approvalStatus: "APPROVED", followUpDate: daysAhead(20), approvedSummary: S({ headline: "Interim COO open to conversations, Dubai interest", capabilities: ["coo", "operations", "turnaround"], sectors: ["logistics", "retail"], engagementPreferences: ["INTERIM", "FRACTIONAL"], locationPreferences: ["dubai", "uk"], currentStatus: "Between engagements", suggestedAvailabilityStatus: "OPEN_TO_CONVERSATIONS", ratesOrSalary: "£1,800/day", workingCharacteristics: ["Blunt", "Thrives in crisis"], strengths: ["Operations turnaround"], avoid: ["Steady-state roles"], summary: "Open to interim COO or fractional; Dubai possible." }) }, 1),
    C("emma", "u-waqas", { date: daysAgo(9), type: "IN_PERSON", rawNotes: "Coffee with Emma. Quietly exploring — frustrated by lack of progression. Would move for Head of Reg Change or a step up. £175k now. Only London. Strict confidentiality.", approvalStatus: "DRAFT" }, 1),
    C("hannah", "u-waqas", { date: daysAgo(22), type: "INTRO_CALL", rawNotes: "Intro via Daniel. Hannah leads AI at a Nordic bank. Only the right opportunity — fractional advisory on responsible AI, especially for Gulf institutions. £1,900/day.", approvalStatus: "NEEDS_REVIEW", aiSummary: S({ headline: "Head of AI, right-opportunity-only, fractional advisory interest", capabilities: ["ai", "genai", "governance"], sectors: ["banking"], engagementPreferences: ["ADVISORY", "FRACTIONAL"], locationPreferences: ["london", "uae"], currentStatus: "In role; selective", suggestedAvailabilityStatus: "RIGHT_OPPORTUNITY_ONLY", ratesOrSalary: "£1,900/day", constraints: ["Only Group-level roles for a permanent move"], strengths: ["Responsible AI governance"], unresolvedQuestions: ["Capacity — how many days a month?"], summary: "Fractional advisory on responsible AI; selective." }) }, 1),
    C("khalid", "u-richard", { date: daysAgo(30), type: "OPPORTUNITY_DISCUSSION", rawNotes: "Khalid is busy but keen to stay close to Amana. Not looking until Q2 but happy to be on a bid team. AED 5,000/day.", approvalStatus: "APPROVED", followUpDate: daysAhead(45), approvedSummary: S({ headline: "Bid director, not looking until Q2, keep warm", capabilities: ["bid management", "proposal"], sectors: ["government"], engagementPreferences: ["SOW"], locationPreferences: ["dubai"], currentStatus: "Busy until Q2", suggestedAvailabilityStatus: "NOT_LOOKING_KEEP_IN_TOUCH", ratesOrSalary: "AED 5,000/day", constraints: ["Not before Q2"], strengths: ["Winning GCC public sector bids"], summary: "Keep warm for Q2 bids." }) }, 1),
    C("fatima", "u-richard", { date: daysAgo(8), type: "INTRO_CALL", rawNotes: "Fatima available now. GRC for energy and government. AED 4,200/day. Would do UK remote. Contract or SOW.", approvalStatus: "APPROVED", followUpDate: daysAhead(14), approvedSummary: S({ headline: "Cyber GRC consultant available now", capabilities: ["cyber security", "governance", "risk", "compliance"], sectors: ["energy", "government"], engagementPreferences: ["CONTRACT", "SOW"], locationPreferences: ["abu dhabi", "remote"], currentStatus: "Available now", suggestedAvailabilityStatus: "AVAILABLE_NOW", ratesOrSalary: "AED 4,200/day", strengths: ["Regulatory GRC"], unresolvedQuestions: ["Direct evidence of delivery — reference only so far"], summary: "Available now for GRC contract/SOW." }) }, 1),
    C("tom", "u-waqas", { date: daysAgo(12), rawNotes: "Tom has capacity for one more fractional CFO client from next month. Carve-outs and scale-ups. £1,600/day.", approvalStatus: "APPROVED", followUpDate: daysAhead(30), approvedSummary: S({ headline: "Fractional CFO with capacity from next month", capabilities: ["cfo", "finance transformation", "m&a integration"], sectors: ["technology", "retail"], engagementPreferences: ["FRACTIONAL", "ADVISORY"], locationPreferences: ["edinburgh", "uk"], currentStatus: "Capacity for one more client", suggestedAvailabilityStatus: "FRACTIONAL_AVAILABILITY", ratesOrSalary: "£1,600/day", strengths: ["Carve-outs"], summary: "One fractional CFO slot available." }) }, 1),
  ];
  const scheduled: Scheduled[] = [
    { id: "s-1", personId: pid("ben"), ownerId: "u-waqas", provider: "MANUAL", startAt: daysAhead(2), endAt: daysAhead(2), meetingType: "INTRO_CALL", status: "SCHEDULED" },
    { id: "s-2", personId: pid("grace"), ownerId: "u-waqas", provider: "MANUAL", startAt: daysAhead(4), endAt: daysAhead(4), meetingType: "INTRO_CALL", status: "SCHEDULED" },
    { id: "s-3", personId: pid("james"), ownerId: "u-waqas", provider: "MANUAL", startAt: daysAhead(6), endAt: daysAhead(6), meetingType: "CATCH_UP", status: "SCHEDULED" },
  ];
  const relocation: Relocation[] = [
    { personId: pid("priya"), currentLocation: "London, UK", targetLocation: "Abu Dhabi, UAE", targetMoveWindow: "Within 12 months (September school intake)", familyMove: true, schoolGuidanceInterest: true, housingGuidanceInterest: true, relocationAdvisoryInterest: true, employerSponsored: false, advisoryStatus: "DISCOVERY_CALL", notes: "Two children, primary age. Wants British-curriculum schools.", updatedAt: daysAgo(3) },
    { personId: pid("sarah"), currentLocation: "London, UK", targetLocation: "Dubai, UAE", targetMoveWindow: "6–12 months, client dependent", familyMove: true, schoolGuidanceInterest: false, housingGuidanceInterest: false, relocationAdvisoryInterest: true, employerSponsored: true, advisoryStatus: "INTEREST_CAPTURED", notes: "Would expect the client to sponsor the move.", updatedAt: daysAgo(6) },
    { personId: pid("marcus"), currentLocation: "Leeds, UK", targetLocation: "Dubai, UAE", targetMoveWindow: "Flexible", familyMove: true, schoolGuidanceInterest: false, housingGuidanceInterest: false, relocationAdvisoryInterest: false, employerSponsored: false, advisoryStatus: "INTEREST_CAPTURED", updatedAt: daysAgo(15) },
    { personId: pid("amira"), currentLocation: "Dubai, UAE", targetLocation: "London, UK", targetMoveWindow: "12–18 months", familyMove: false, schoolGuidanceInterest: false, housingGuidanceInterest: true, relocationAdvisoryInterest: true, employerSponsored: true, advisoryStatus: "PROPOSAL_SENT", notes: "Employer-sponsored package discussed with Amana.", updatedAt: daysAgo(35) },
  ];
  const partners: Partner[] = [
    { id: "pt-harbour", name: "Harbour Search", contactName: "Jo Harbour", subscriptionStatus: "ACTIVE", subscriptionTier: "Standard", commercialModel: "SUCCESS_SHARE", commercialSharePct: 15, monthlyFee: 1500, currency: "GBP", licensedForPermanent: true, notes: "Licensed recruiter for permanent placements in UK financial services." },
    { id: "pt-gulf", name: "Gulf Talent Partners", contactName: "Omar Siddiqui", subscriptionStatus: "TRIAL", subscriptionTier: "Trial", commercialModel: "INTRODUCTION_FEE", commercialSharePct: 12.5, monthlyFee: null, currency: "AED", licensedForPermanent: true, notes: "Trial — UAE/KSA permanent and interim." },
  ];
  const O = (id: string, o: Omit<Opportunity, "id" | "createdAt" | "updatedAt" | "currency" | "isAmana"> & { currency?: string; isAmana?: boolean }, ago: number): Opportunity => ({ id, currency: "GBP", isAmana: false, createdAt: daysAgo(ago + 10), updatedAt: daysAgo(ago), ...o });
  const opportunities: Opportunity[] = [
    O("o-1", { sourceType: "AMANA", clientName: "Tier-1 UK bank (via Amana)", title: "Stabilise a core banking transformation and challenge the SI", problemStatement: "A £120m core banking replacement is six months late. The client needs someone to take control of the programme, re-baseline the systems integrator and rebuild board confidence.", desiredOutcomes: "Credible re-baselined plan in 60 days; SI contract renegotiated; board reporting restored.", engagementRoute: "SOW", location: "London (hybrid)", duration: "12 months", startDate: daysAhead(30), budget: 1400, requiredCapabilities: ["Programme director", "Systems integrator challenge", "Turnaround"], preferredCapabilities: ["PMO", "Regulatory"], sectors: ["Banking"], seniority: "DIRECTOR", status: "SHORTLIST", isAmana: true }, 2),
    O("o-2", { sourceType: "PARTNER", partnerId: "pt-harbour", clientName: "UK insurer (via Harbour Search)", title: "Group CISO", problemStatement: "Insurer needs a Group CISO after a regulatory finding on identity and access controls. Permanent hire; must be credible with the FCA.", desiredOutcomes: "Remediation plan accepted by regulator; identity programme delivered.", engagementRoute: "PERMANENT", location: "Manchester / London", startDate: daysAhead(90), budget: 190000, requiredCapabilities: ["CISO", "Identity and access", "Regulatory"], preferredCapabilities: ["Security architecture"], sectors: ["Insurance"], seniority: "EXECUTIVE", status: "MATCHING" }, 4),
    O("o-3", { sourceType: "DIRECT_CLIENT", clientName: "Meridian Energy", title: "Fractional operations lead for Gulf expansion", problemStatement: "Meridian is opening a Dubai operation and needs someone two to three days a week to build the operating model and hire the local team.", desiredOutcomes: "Operating model designed; first five hires made; handover to local COO in nine months.", engagementRoute: "FRACTIONAL", location: "Dubai", duration: "9 months", startDate: daysAhead(45), budget: 1700, requiredCapabilities: ["Operations", "Target operating model"], preferredCapabilities: ["Turnaround", "Supply chain"], sectors: ["Energy"], seniority: "EXECUTIVE", status: "MATCHING" }, 5),
    O("o-4", { sourceType: "AMANA", clientName: "Abu Dhabi government entity (via Amana)", title: "Cyber GRC uplift — proposal team", problemStatement: "Amana is bidding for a 6-month GRC uplift. Need a GRC lead and a bid director for the proposal, plus an architecture reviewer.", desiredOutcomes: "Winning proposal submitted in three weeks; team ready to mobilise.", engagementRoute: "SOW", location: "Abu Dhabi", duration: "6 months", startDate: daysAhead(60), budget: 4500, currency: "AED", requiredCapabilities: ["Cyber security", "Governance", "Risk", "Compliance"], preferredCapabilities: ["Bid management", "Enterprise architecture"], sectors: ["Government"], seniority: "MANAGER", status: "QUALIFYING", isAmana: true }, 1),
    O("o-5", { sourceType: "FOUNDER", clientName: "Private equity portfolio company", title: "Fractional CFO for a carve-out", problemStatement: "Portfolio company being carved out of a larger group needs a fractional CFO to stand up finance, two days a week.", engagementRoute: "FRACTIONAL", location: "Remote / Edinburgh", duration: "6 months", budget: 1600, requiredCapabilities: ["CFO", "M&A integration", "Finance transformation"], preferredCapabilities: [], sectors: ["Technology"], seniority: "EXECUTIVE", status: "INTAKE" }, 0),
    O("o-6", { sourceType: "AMANA", clientName: "Utility (via Amana)", title: "SAP S/4 programme assurance", problemStatement: "Independent assurance of an S/4 programme ahead of go-live decision.", engagementRoute: "ADVISORY", location: "Birmingham", duration: "8 weeks", budget: 1300, requiredCapabilities: ["SAP", "ERP", "Programme management"], preferredCapabilities: ["Vendor management"], sectors: ["Utilities"], seniority: "DIRECTOR", status: "CLOSED_WON", isAmana: true }, 40),
  ];
  const introductions: Introduction[] = [
    { id: "i-1", opportunityId: "o-1", personId: pid("sarah"), requestedById: "u-richard", approvedById: "u-waqas", consentStatus: "GRANTED", status: "INTRODUCED", route: "SOW", commercialModel: "AMANA_SOW", commercialValue: 300000, currency: "GBP", notes: "Introduced to Amana engagement lead; client meeting booked.", createdAt: daysAgo(2) },
    { id: "i-2", opportunityId: "o-2", personId: pid("daniel"), requestedById: "pt-harbour", consentStatus: "REQUESTED", status: "REQUESTED", route: "PERMANENT", recruitmentPartnerId: "pt-harbour", commercialModel: "SUCCESS_SHARE", commercialSharePct: 15, commercialValue: 190000, currency: "GBP", notes: "Partner requested identity reveal. Waiting on Daniel's consent — not before Q1.", createdAt: daysAgo(5) },
    { id: "i-3", opportunityId: "o-3", personId: pid("marcus"), requestedById: "u-waqas", approvedById: "u-waqas", consentStatus: "GRANTED", status: "APPROVED", route: "FRACTIONAL", commercialModel: "INTRODUCTION_FEE", commercialValue: 15000, currency: "GBP", createdAt: daysAgo(3) },
  ];
  const team: TeamMember[] = [
    { id: "t-1", opportunityId: "o-4", personId: pid("fatima"), roleOnTeam: "GRC lead" },
    { id: "t-2", opportunityId: "o-4", personId: pid("khalid"), roleOnTeam: "Bid director", notes: "Keep-warm status; check Q2 capacity" },
    { id: "t-3", opportunityId: "o-4", personId: pid("layla"), roleOnTeam: "Architecture reviewer (advisory)" },
  ];
  const requirements: PartnerRequirement[] = [
    { id: "q-1", partnerId: "pt-harbour", title: "Group CISO — UK insurer", description: "Permanent Group CISO following a regulatory finding on identity and access.", engagementRoute: "PERMANENT", location: "Manchester / London", requiredCapabilities: ["CISO", "Identity and access", "Regulatory"], seniority: "EXECUTIVE", budget: "£180–200k", status: "INTRO_REQUESTED", linkedOpportunityId: "o-2", createdAt: daysAgo(6) },
    { id: "q-2", partnerId: "pt-harbour", title: "Head of Regulatory Change — bank", description: "Permanent hire for a UK bank; must have run a large regulatory programme.", engagementRoute: "PERMANENT", location: "London", requiredCapabilities: ["Regulatory", "Programme management", "Change management"], seniority: "DIRECTOR", budget: "£170k", status: "SUBMITTED", createdAt: daysAgo(2) },
  ];
  const accounts: Account[] = [
    { id: "ac-amana", name: "Amana Expert Network", kind: "EXPERT_NETWORK", contactName: "Richard Cole", status: "ACTIVE", currency: "GBP", portalEnabled: true, notes: "Sister consultancy. SOW resourcing and expert calls.", createdAt: daysAgo(300) },
    { id: "ac-harbour", name: "Harbour Search", kind: "AGENCY", contactName: "Jo Harbour", contactEmail: "jo@harboursearch.example", status: "ACTIVE", currency: "GBP", partnerId: "pt-harbour", monthlyFee: 1500, portalEnabled: true, notes: "Licensed UK recruiter. Pays a referral share on perm and a margin share on contract.", createdAt: daysAgo(200) },
    { id: "ac-gulf", name: "Gulf Talent Partners", kind: "AGENCY", contactName: "Omar Siddiqui", status: "ACTIVE", currency: "AED", partnerId: "pt-gulf", portalEnabled: true, notes: "UAE / KSA agency. Trial converted.", createdAt: daysAgo(90) },
    { id: "ac-meridian", name: "Meridian Energy", kind: "CLIENT", contactName: "Sophie Grant", status: "ACTIVE", currency: "GBP", portalEnabled: true, createdAt: daysAgo(120) },
    { id: "ac-clienta", name: "Client A · Dubai retail bank", kind: "CLIENT", contactName: "Hamad Al Mazrouei", status: "PROSPECT", currency: "AED", portalEnabled: true, notes: "Direct client. Perm hires, pays a success fee.", createdAt: daysAgo(14) },
  ];
  const B = (id: string, accountId: string, text: string, over: Partial<StoredBrief>, ago: number): StoredBrief => { const parsed = parseBrief(text); const kind = accounts.find((a) => a.id === accountId)!.kind; const model = defaultFeeModel(parsed.engagementRoute, kind); return { ...parsed, id, accountId, submittedVia: "OWNER", status: "SEARCHING", terms: defaultTerms(DEFAULT_RATE_CARD, model), termsAccepted: false, createdAt: daysAgo(ago), updatedAt: daysAgo(ago), ...over }; };
  const briefs: StoredBrief[] = [
    B("b-1", "ac-gulf", "Gulf Talent Partners is looking for 2 BAs already in Dubai with a visa, perm, retail banking, AED 360k, start asap", { submittedVia: "PORTAL", status: "SHORTLISTED", openToMembers: true, memberSummary: "Two permanent business analysts for a retail bank in Dubai. Must already be in the UAE with the right to work. Payments or core banking experience helps." }, 3),
    B("b-2", "ac-clienta", "Client A wants a perm project manager for a digital banking programme in Dubai, AED 480k, senior, start in January", { status: "QUALIFYING" }, 1),
    B("b-3", "ac-amana", "Expert call: 2 hours with someone who has run an SAP S/4 go-live assurance review for a utility, £600/hour, this week", { status: "INTRODUCING", expertHours: 2, termsAccepted: true }, 6),
    B("b-4", "ac-meridian", "Fractional operations lead 2 days a week to build the Dubai operating model, £1,700/day, 9 months, must be willing to spend time in Dubai", { status: "SEARCHING", termsAccepted: true, openToMembers: true, memberSummary: "Fractional operations lead, two days a week for nine months, building a Dubai operating model for an energy company. Needs someone who has built an operation from scratch and will spend time on the ground." }, 12),
    B("b-0", "ac-meridian", "Interim COO for a 6-month operations turnaround in Aberdeen, £1,400/day, start immediately", { status: "FILLED", termsAccepted: true }, 74),
  ];

  /**
   * Shortlist history. Without this the funnel on the Performance page is a single bar and four
   * zeros, which is honest but tells you nothing about what the page does. These are the same
   * shapes the app writes itself when you work a requirement through.
   */
  const SL = (id: string, briefId: string, key: string, decision: ShortlistDecision, fit: number, why: string, ago: number, moved = ago): ShortlistItem => ({
    id, briefId, personId: pid(key), fitScore: fit, fitExplanation: why,
    dimensions: [{ name: "Capability", score: fit, note: why }], uncertainty: [], checks: [],
    tier: fit >= 70 ? "meets" : fit >= 50 ? "conversation" : "stretch",
    decision, createdAt: daysAgo(ago), updatedAt: daysAgo(moved),
  });
  const shortlist: ShortlistItem[] = [
    SL("sl-1", "b-0", "marcus", "PLACED", 84, "Interim COO who has run exactly this kind of turnaround.", 72, 58),
    SL("sl-2", "b-0", "grace", "CLIENT_PASSED", 61, "Strong operator, but no energy sector behind her.", 72, 66),
    SL("sl-3", "b-1", "nadia", "PLACED", 79, "Core banking BA already in Dubai on a residence visa.", 40, 24),
    SL("sl-4", "b-1", "omar", "CLIENT_INTERESTED", 74, "Retail banking product owner, in Dubai, available now.", 3, 1),
    SL("sl-5", "b-1", "isha", "PROPOSED", 66, "Payments BA, would need a visa moved across.", 3, 3),
    SL("sl-6", "b-3", "james", "INTRODUCED", 88, "Ran the S/4 assurance review the brief describes.", 6, 2),
    SL("sl-7", "b-4", "marcus", "PROPOSED", 71, "Has built a Gulf operating model from nothing before.", 10, 9),
    SL("sl-8", "b-4", "hannah", "CANDIDATE", 58, "Adjacent — operations, but never fractional.", 10, 10),
  ];

  const fees: FeeLine[] = [
    { id: "f-0", briefId: "b-0", accountId: "ac-meridian", personId: pid("marcus"), model: "CONTRACT_MARGIN", basis: "12% of £1,400/day \u00d7 130 days", gross: 182000, ourTake: 21840, currency: "GBP", status: "PAID", createdAt: daysAgo(58), updatedAt: daysAgo(20) },
    { id: "f-5", briefId: "b-1", accountId: "ac-gulf", personId: pid("nadia"), model: "AGENCY_REFERRAL", basis: "35% of the agency\u2019s 20% fee on AED 360,000", gross: 72000, ourTake: 25200, currency: "AED", status: "INVOICED", createdAt: daysAgo(24), updatedAt: daysAgo(6) },
    { id: "f-1", briefId: "b-3", accountId: "ac-amana", personId: pid("james"), model: "EXPERT_HOURLY", basis: "30% of £600/hour × 2 hours", gross: 1200, ourTake: 360, currency: "GBP", status: "AGREED", createdAt: daysAgo(2), updatedAt: daysAgo(2) },
    { id: "f-2", briefId: "b-4", accountId: "ac-meridian", personId: pid("marcus"), model: "CONTRACT_MARGIN", basis: "12% of £1,700/day × 165 days (9 mo)", gross: 280500, ourTake: 33660, currency: "GBP", status: "FORECAST", createdAt: daysAgo(10), updatedAt: daysAgo(10) },
    { id: "f-3", briefId: "b-1", accountId: "ac-gulf", personId: null, model: "AGENCY_REFERRAL", basis: "35% of the agency's 20% fee on AED 360,000 × 2 people", gross: 144000, ourTake: 50400, currency: "AED", status: "FORECAST", createdAt: daysAgo(3), updatedAt: daysAgo(3) },
    { id: "f-4", briefId: "b-3", accountId: "ac-amana", personId: pid("sarah"), model: "SOW_SHARE", basis: "10% of £300,000 SOW value", gross: 300000, ourTake: 30000, currency: "GBP", status: "INVOICED", createdAt: daysAgo(40), updatedAt: daysAgo(12) },
  ];
  const vouches: Vouch[] = [
    { id: "v-1", personId: pid("sarah"), voucherId: "u-waqas", voucherKind: "USER", context: "Core banking recovery, 2021–22", statement: "The only person the SI was afraid of. I would put her into any red programme.", wouldRecommend: true, attributes: { assertiveness: 5, conflict: 5, political: 5, commercial: 4, influence: 5 }, createdAt: daysAgo(300) },
    { id: "v-0", personId: pid("sarah"), voucherId: "ext-1", voucherKind: "EXTERNAL", voucherName: "Former CIO, Tier-1 bank", source: "LinkedIn recommendation", context: "Core banking programme", statement: "Sarah re-baselined a failing programme and restored the board's confidence within a quarter.", wouldRecommend: true, createdAt: daysAgo(500) },
    { id: "v-2", personId: pid("sarah"), voucherId: pid("priya"), voucherKind: "PERSON", context: "Worked under her on the NHS operating model", statement: "Calm, direct, and the board listened to her.", wouldRecommend: true, attributes: { assertiveness: 5, conflict: 4, political: 4, collaboration: 3, influence: 5 }, createdAt: daysAgo(90) },
    { id: "v-3", personId: pid("sarah"), voucherId: pid("tom"), voucherKind: "PERSON", context: "Carve-out finance workstream", statement: "Kept the whole programme honest.", wouldRecommend: true, createdAt: daysAgo(45) },
    { id: "v-4", personId: pid("nadia"), voucherId: "u-waqas", voucherKind: "USER", context: "Payments platform programme, Dubai", statement: "Requirements were the one thing that never slipped.", wouldRecommend: true, attributes: { assertiveness: 4, conflict: 3, political: 4, commercial: 3, collaboration: 5, pace: 4 }, createdAt: daysAgo(200) },
    { id: "v-5", personId: pid("nadia"), voucherId: pid("omar"), voucherKind: "PERSON", context: "Worked under her on payments", statement: "Taught me how to run a requirements workshop properly.", wouldRecommend: true, createdAt: daysAgo(20) },
    { id: "v-6", personId: pid("priya"), voucherId: "u-waqas", voucherKind: "USER", context: "NHS trust operating model", wouldRecommend: true, createdAt: daysAgo(400) },
    { id: "v-7", personId: pid("priya"), voucherId: "u-soban", voucherKind: "USER", context: "Amana public sector SOW", wouldRecommend: true, createdAt: daysAgo(100) },
    { id: "v-8", personId: pid("marcus"), voucherId: "u-waqas", voucherKind: "USER", context: "Logistics turnaround", wouldRecommend: true, attributes: { assertiveness: 5, conflict: 5, political: 2, commercial: 5, ambiguity: 5, pace: 5 }, createdAt: daysAgo(900) },
    { id: "v-9", personId: pid("khalid"), voucherId: "u-richard", voucherKind: "USER", context: "Two Amana bids", wouldRecommend: true, createdAt: daysAgo(150) },
    { id: "v-10", personId: pid("omar"), voucherId: pid("nadia"), voucherKind: "PERSON", context: "Payments hub, ran the BA workstream with me", statement: "Fast, thorough, and the business trusted him.", wouldRecommend: true, createdAt: daysAgo(15) },
  ];
  const referrals: Referral[] = [
    { id: "rf-1", referrerPersonId: pid("nadia"), referredPersonId: pid("omar"), name: "Omar Haddad", context: "Worked under me on the payments hub", note: "Would suit the Dubai BA requirement.", briefId: "b-1", status: "ACCEPTED", createdAt: daysAgo(6), updatedAt: daysAgo(4) },
    { id: "rf-2", referrerPersonId: pid("sarah"), name: "Ben Hughes", email: "ben@example.com", context: "Ran programme recovery for me on the insurance programme", note: "Good with systems integrators.", status: "NEW", createdAt: daysAgo(2), updatedAt: daysAgo(2) },
  ];
  const pitches: Pitch[] = [
    { id: "pi-1", briefId: "b-4", personId: pid("marcus"), note: "I built the Gulf operation for a logistics group from nothing, and I know what breaks in month three.", route: "FRACTIONAL", availableFrom: "From the first week of next month", rate: "£1,800/day", relevantWork: "Stood up a logistics operation in Dubai from zero to 40 people in nine months, including the local hiring.", status: "SUBMITTED", createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  ];
  const audit: AuditEntry[] = [
    { id: "a-1", actorId: "u-waqas", action: "summary.approve", entityType: "Conversation", entityId: "c-priya-1", detail: "Priya Natarajan", createdAt: daysAgo(3) },
    { id: "a-2", actorId: "u-waqas", action: "introduction.approve", entityType: "Introduction", entityId: "i-1", detail: "Sarah Okonkwo → Stabilise a core banking transformation", createdAt: daysAgo(2) },
    { id: "a-3", actorId: "u-richard", action: "team.add", entityType: "Opportunity", entityId: "o-4", detail: "Fatima Al Rashid", createdAt: daysAgo(1) },
    { id: "a-4", actorId: "u-waqas", action: "integration.connect", entityType: "SchedulingConnection", detail: "MANUAL", createdAt: daysAgo(30) },
  ];
  return { users: USERS, me: USERS[0], people, relationships, evidence, conversations, scheduled, opportunities, matches: [], introductions, team, partners, requirements, relocation, audit, accounts, briefs, shortlist, fees, rateCard: { ...DEFAULT_RATE_CARD }, vouches, referrals, pitches, viewAs: { role: "OWNER" }, screeningScript: JSON.parse(JSON.stringify(SCREENING_SCRIPT)), connections: ["MANUAL"] };
}
